name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le code
      uses: actions/checkout@v2

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

    - name: Exécuter les tests
      run: |
        pytest

